# Welcome to your Python notebook

This notebook was created for your project.

In [ ]:
print('Hello from Jupyter!')
x = 10
y = 20
print(x + y)

Hello from Jupyter!
30


In [ ]:
def display():
    x=10
    print(x)
display()

10


In [1]:
T =10
while T>0:
    print(T)
    if T%2 ==0:
        print(f"{T} is Even Number")
        
        
    T -= 1

10
10 is Even Number
9
8
8 is Even Number
7
6
6 is Even Number
5
4
4 is Even Number
3
2
2 is Even Number
1


In [2]:
x = 8

if x > 5:
    print("A")

if x > 10:
    print("B")
else:
    print("C")

A
C


In [3]:
age=20
if age>=18:
    print("Eligible")
else:
    print("Not")

Eligible


In [ ]:
age = 20

if age >= 18:
    print("Eligible")
else:
    print("Not eligible")

SyntaxError: expected ':' (1027784013.py, line 3)

In [7]:
i=1
while(i<=5):
    print(i)
    i+=1

1
2
3
4
5


In [ ]:
n = int(input("Enter the number: "))
if n < 0 or n > 100:
    print("Invalid")
elif n >= 90 and n <= 100:
    print("Excellent")
elif n > 75 and n < 90:
    print("Good")
elif n >= 50 and n <= 75:
    print("Pass")
else:
    print("Fail")

KeyboardInterrupt: Interrupted by user

In [12]:
import numpy as np
a= np.array([1,10,20,30,40,50]).reshape([2,3])
print(a)

[[ 1 10 20]
 [30 40 50]]


In [26]:
arr=np.array([5,12,8,21,3,17])
a= arr[arr>10]
print(a)


[12 21 17]


In [21]:
a=np.array([[1,2,3],[4,5,6],[8,9,0]])
b=np.array([1,0,1])
c=a+b
print(c)

[[2 2 4]
 [5 5 7]
 [9 9 1]]


In [19]:
import numpy as np
def array(arr):
    mean = np.mean(arr)
    std=np.std(arr)
    if std ==0 :
        return np.zeros(arr)
    return (arr-mean)/std